import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const workSans = Work_Sans({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={workSans.className + " bg-background text-foreground"}>
        <Navigation />
        <div className="pt-15"></div>
        {children}
        <div className="pt-20"></div>
        <Footer />
      </body>
    </html>
  );
}


